config/routes.rb
App::Application.routes.draw do
  devise_for :users
  resources :users, only: [:index]
  resources :videos
  resources :comments
  get '/users/show/:id', to: 'users#show', as: 'users_show'
  get "home/index"
  get "users/index"

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :video

  validates :comment, length: {within: 20 ... 500 }
end

app/models/comments.rb
class Comments < ActiveRecord::Base
  belongs_to :user
  belongs_to :video
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   validates :account_name, uniqueness: true
   validates_inclusion_of :age, :in => 18...100 , :message => 'Must be between 18 and 100 years old to join... Sorry Grandma!'

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true, uniqueness: true
end

app/models/youtube_it.rb
class YoutubeIt < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :account_name, 
  		:password, :password_confirmation, :location, :age)}
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :account_name, 
  		:password, :password_confirmation, :current_password, :location, :age)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comment = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
  	@comment = Comment.new(comment_params)
  	if @comment.save
      Notifications.new_comment(@comment).deliver
  		redirect_to videos_path
  	else
  		render 'new'
  	end
  end
  
  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to comment_path(@comment.id)
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end

  private
  def comment_params
  	params.require(:comment).permit(:user_id, :comment, :video_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
    @comment = Comment.new
    @comments = Comment.order(created_at: :desc).where(video_id: params[:id]).limit(4)
  end

  private 
  def video_params
  	params.require(:video).permit(:file, :user_id, :name)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to users_path
  	else 
  		render 'new'
  	end
  end

  def show
    @user = User.find(params[:id])
    @videos = Video.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
  	params.require(:user).permit(:account_name, :location, :age, :email, :password)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def new
    if user_signed_in?
  	 @video = Video.new
    else 
      redirect_to new_user_session_path
    end
  end

  def create
  	@video = Video.new(video_params)
  	if @video.user.id != current_user.id
        redirect_to root_path
    else 
      if @video.save
  		  redirect_to videos_path
  	   else 
  		   render 'new'
  	   end
    end
  end

  def show
    @video = Video.find(params[:id])
    @comment = Comment.new
    @comments = Comment.order(created_at: :desc).where(video_id: params[:id]).limit(4)
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.user_id != current_user.id
      render 'edit'
    else
      if @video.update_attributes(video_params)
        redirect_to video_path(@video.id)
      else
        render 'edit'
      end
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to videos_path
  end

  private 
  def video_params
  	params.require(:video).permit(:file, :user_id, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/edit.html.erb
<%= form_for(@comment) do |f| %>
	<div class="field">
		<p>Comment: </p>
		<%= f.text_area :comment%>
	</div>

	<div class="actions">
		<%= f.submit%>
	</div>
<% end %> 

app/views/comments/index.html.erb
<table>
	<tr>
		<td>user</td>
		<td>comment</td>
		<td>video</td>
	</tr>
	<% @comment.each do |comment|%>
	<tr>
		<td><%= comment.user.account_name unless comment.user.nil? %></td>
		<td><%= comment.comment %></td>
		<td><%= comment.video.name unless comment.video.nil? %></td>
		<td><%= link_to "edit comment", edit_comment_path(comment.id)%></td>
		<td><%= button_to "delete comment", comment, method: :delete %></td>
	</tr>
	<% end %>
</table>

app/views/comments/new.html.erb
<%= form_for @comment do|f| %>
	<div> 
    	<% if @comment.errors.any? %>
      		<ul>
        		<% @comment.errors.full_messages.each do |msg| %>
          		<li class="error_msg"><%= msg %></li>
        		<% end %>
      		</ul>
      	<% end %>
  	</div>

	<div class="field">
		<%= f.hidden_field :user_id, :value => current_user.id %>
	</div>

	<div class="field">
		<p>comment</p>
		<%=f.text_area :comment%>
	</div>
	
	<div class="field">
		<p>video</p>
		<%=f.collection_select :video_id, Video.all, :id, :name %>
	</div>
	
	<div class="actions">
		<%=f.submit%>
	</div>
<%end%>

app/views/comments/show.html.erb
<div>
	<p>User: <%= @comment.user.account_name%></p>
	<p>Comment: <%= @comment.comment %></p>
	<p>Video: <%= @comment.video.name %></p>
	<p><%= %></p>
</div>

app/views/home/index.html.erb
<div class="content">
	<h2>Welcome to Brad's App</h2>

	<p>View current users' videos or sign up to share videos and comment on others, or by following the links below:</p>


	<ul>
		<li> <%= link_to "Make a new user", new_user_registration_path, class:"body_link" %> </li>
		<li> <%= link_to "List all users", users_index_path, class:"body_link" %> </li>

		<% if user_signed_in? %>
		<li> <%= link_to "Post a new video", new_video_path, class:"body_link" %> </li>
		<% end %>
		<li> <%= link_to "List all videos", videos_path, class:"body_link" %> </li>
</div>

<h2>Videos:</h2>
<div class="videos_home">
	<% @videos.each do |video|%>
	<div class="box">	
		<h4><%= link_to video.name, video_path(video.id), class: "video_link" %> </h4>
		<%= video_tag video.file, :controls => true, class: "video_box" %>
		<p>Posted by <%= link_to video.user.account_name, users_show_path(video.user.id) %></p>

		<% if video.user == current_user %>
			<p><%= button_to "delete video", video, confirm: "Are you sure you want to delete this video?", method: :delete %>
			<%= button_to "edit video", edit_video_path(video) %></p>
		<% end %>
	</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="https://ucarecdn.com/widget/1.0.1/uploadcare/uploadcare-1.0.1.min.js" charset="utf-8"></script>
  <script type="text/javascript"> UPLOADCARE_PUBLIC_KEY = '63f82a767f4957b67974'
  UPLOADCARE_AUTOSTORE = true;
  </script>

</head>
<body>

	<div class="nav_bar">
		<div id="left_options">
			<ul>
				<li class="head_list"><%= link_to "Home", root_path, class: "head_link", id: "home" %></li>
				<li class="head_list"><%= link_to "All Users", users_index_path, class: "head_link", id: "users" %> </li>
				<li class="head_list"> <%= link_to "All Videos", videos_path, class: "head_link", id:"videos" %> </li>
			</ul>
		</div>
		<div id="right_opt">
			<ul>
				<% if user_signed_in? %>
					<li class="head_list"><%= link_to 'Logout', destroy_user_session_path, :method => :delete, :class => "head_link" %></li>
					<li class="head_list"><%= link_to "Edit User", edit_user_registration_path, :class => "head_link" %></li>
				<% else %>
					<li class="head_list"><%= link_to 'Login', new_user_session_path, :class => "head_link" %></li>
				<% end %>
			</ul>
			<div id="dropdown">
				<p class="notice"> <%= notice %></p>
				<p class="alert"> <%= alert %></p>
			</div>
		</div>
	</div>

<div class="content">
	<%= yield %>
</div>

	<div class="footer">
		<p class="contact">Contact me at blowenstein93@gmail.com for more information about this app</p>
	</div>

</body>
</html>

app/views/notifications/new_comment.html.erb
<h2><%= @greeting %></h2>


<p> <a href = <%= users_path(@commentor.id) %>><%= @commentor.account_name%></a>
just said something about your video. Check it out <%= link_to 'here', comment_url(@id) %> </p>


<p>Thanks! And enjoy playing with the app!</p>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
	<div class="field">
		<p>Account Name: </p>
		<%= f.text_field :account_name%>
	</div>
	<div class="field">
		<p>email</p>
		<%= f.text_field :email%>
	</div>
	<div class="field">
		<p>password</p>
		<%= f.password_field :password%>
	</div>
	<div class="field">
		<p>age</p>
		<%= f.text_field :age%>
	</div>
	<div class="field">
		<p>location</p>
		<%= f.text_field :location%>
	</div>	

	<div class="actions">
		<%= f.submit%>
	</div>
<% end %> 

app/views/users/index.html.erb
<table>
	<tr>
		<td>user name</td>
		<td>email</td>
		<td>location</td>
		<td>age</td>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td><%= link_to user.account_name, users_show_path(user.id) %></td>
		<td><%= user.email %></td>
		<td><%= user.location %></td>
		<td><%= user.age %></td>
		<% if user == current_user %>
			<td><%= link_to "edit your account", edit_user_registration_path %></td>
		<% end %>
	</tr>
	<% end %>
</table>

app/views/users/new.html.erb
<%=form_for @user do|f| %>
	<div class="field">
		<p>account name</p>
		<%=f.text_field :account_name%>
	</div>
	<div class="field">
		<p>email</p>
		<%=f.text_field :email%>
	</div>
	<div class="field">
		<p>password</p>
		<%=f.text_field :password%>
	</div>
	<div class="field">
		<p>location</p>
		<%=f.text_field :location%>
	</div>
	<div class="field">
		<p>age</p>
		<%=f.text_field :age%>
	</div>

	<div class="actions">
		<%=f.submit%>
	</div>
	
<%end%>

app/views/users/show.html.erb
<h2>User Page</h2>

<div>
	<p>Username: <%= @user.account_name %></p>
	<p>Email: <%= @user.email %></p>
	<p>Age: <%= @user.age %> </p>
	<p>Location: <%= @user.location %> </p>

	<% if @user == current_user %>
		<p><%= link_to "edit user", edit_user_registration_path %> </p>
	<% end %>

	<h2>Videos:</h2>
	<% @videos.each do |video| %>
		<div class="users_videos">
			<h3 class="user_vid"><%= link_to video.name, video_path(video.id) %></h3>
			<%= video_tag video.file, :controls => true , class: "user_vid"%>
		</div>
	<% end %>
</div>

app/views/videos/edit.html.erb
<%= form_for(@video) do |f| %>
	
	<div class="field">
		<p>Video Name: </p>
		<%= f.text_field :name%>
	</div>

	<div class="actions">
		<%= f.submit%>
	</div>
<% end %>

app/views/videos/index.html.erb
<h2>Videos:</h2>

	<% @videos.each do |video|%>
	<div class="box">	
		<h4><%= link_to video.name, video_path(video.id), class: "video_link" %> </h4>
		<%= video_tag video.file, :controls => true, class: "video_box" %>
		<p>Posted by <%= link_to video.user.account_name, users_show_path(video.user.id) %></p>

		<% if video.user == current_user %>
			<p><%= button_to "delete video", video, confirm: "Are you sure you want to delete this video?", method: :delete %> </p>
			<p><%= link_to "edit video", edit_video_path(video.id) %></p>
		<% end %>
	</div>
	<% end %>

app/views/videos/new.html.erb
<%=form_for @video do|f| %>

  	<div > 
    	<% if @video.errors.any? %>
      		<ul>
        		<% @video.errors.full_messages.each do |msg| %>
          		<li class="error_msg"><%= msg %></li>
        		<% end %>
      		</ul>
      	<% end %>
  	</div>

  	<div class="field">
  		<p>Upload Your Video</p>
  		<div>
	  		<%= f.uploadcare_field :file %>
		</div>
	</div>

	<div class="field">
		<%= f.hidden_field :user_id, :value => current_user.id %>
	</div>
	
	<div class="field">
		<p>Video Name</p>
		<%= f.text_field :name %>
	</div>

	<div class="actions">
		<%=f.submit%>
	</div>
<% end %>

app/views/videos/show.html.erb
<div id="video_content">
	<h2>Video: "<%= @video.name %>"</h2>
	<p><%= video_tag @video.file, :controls => true, class: "video_box" %> </p>
	<p>Posted by <%= link_to @video.user.account_name, users_show_path(@video.user.id), class: "video_link" %></p>

</div>




<button id="toggle_comments">Hide Comments</button>

<div class="comment_list">
<% @comments.each do |f|%>
	<div class="vid_comment">
		<h5>Posted by: <%= f.user.account_name %></h5>
		<p><%=f.comment%></p>
	</div>
<% end %>
</div>

<% if user_signed_in? %>
	<%= form_for(@comment) do |f| %>
		<div class="field">
			<%= f.hidden_field :user_id, :value => current_user.id %>
		</div>

		<div class="field">
			<p>Post a new comment!</p>
			<%=f.text_area :comment %>
		</div>
		
		<div class="field">
			<%=f.hidden_field :video_id, :value => @video.id %>
		</div>
		
		<div class="actions">
			<%=f.submit%>
		</div>
	<% end %>	
<%end%>